## **Analysis and Data Cleaning**

##### **BATTING**

In [2]:
import pandas as pd

In [62]:
# Batting Stats
batting = pd.read_csv("batting_stats.csv")
batting.head()

,match_no,match,innings,batsman,dismissal,runs,balls,minutes,4s,6s,strike_rate
0,1,Janakpur Bolts vs Kathmandu Gorkhas,1,Lahiru Milantha †,c †Simpson b Milind Kumar,7,12,-,1,0,58.33
1,1,Janakpur Bolts vs Kathmandu Gorkhas,1,Aasif Sheikh,st †Simpson b Shahab Alam,54,41,-,6,1,131.70
2,1,Janakpur Bolts vs Kathmandu Gorkhas,1,Anil Sah (c),c Erasmus b Milind Kumar,0,2,-,0,0,0.00
3,1,Janakpur Bolts vs Kathmandu Gorkhas,1,Jan Nicol Loftie-Eaton,b Milind Kumar,2,8,-,0,0,25.00
4,1,Janakpur Bolts vs Kathmandu Gorkhas,1,Sanjay Krishnamurthi,b Santosh Yadav,2,6,-,0,0,33.33

In [63]:
batting.shape

(340, 11)

In [64]:
batting['out/ not_out'] = batting['dismissal'].apply(lambda x: "not out" if x == 'not out' else "out")

In [65]:
batting.drop('dismissal',axis=1, inplace=True)
batting.drop('minutes',axis=1, inplace=True)

In [66]:
batting.columns

Index(['match_no', 'match', 'innings', 'batsman', 'runs', 'balls', '4s', '6s',
       'strike_rate', 'out/ not_out'],
      dtype='object')

In [67]:
batting['batsman'] = batting['batsman'].str.replace(r'†', '', regex=True)

In [70]:
batting.sample(5)

,match_no,match,innings,batsman,runs,balls,4s,6s,strike_rate,out/ not_out
267,16,Biratnagar Kings vs Karnali Yaks,1,Priyank Panchal,63,47,6,2,134.04,out
308,18,Janakpur Bolts vs Sudur Paschim Royals,2,Chris Lynn,1,5,0,0,20.00,out
302,18,Janakpur Bolts vs Sudur Paschim Royals,1,Aaditya Mahata,15,13,2,0,115.38,out
52,4,Kathmandu Gorkhas vs Sudur Paschim Royals,1,Naren Saud,6,12,0,0,50.00,out
316,19,Karnali Yaks vs Kathmandu Gorkhas,1,Najibullah Zadran,12,14,0,1,85.71,out

In [71]:
print(f"Shape: {batting.shape}")
print("===========================")
print(f"Checking datatypes: \n\n {batting.dtypes}")

Shape: (340, 10)
===========================
Checking datatypes:

 match_no         int64
match           object
innings          int64
batsman         object
runs             int64
balls            int64
4s               int64
6s               int64
strike_rate     object
out/ not_out    object
dtype: object

In [90]:
# Changing dtype of strike_rate
# batting['strike_rate'] = batting['strike_rate'].astype(float)
batting["strike_rate"] = pd.to_numeric(batting["strike_rate"], errors='coerce')

In [ ]:
batting['strike_rate'] = batting['strike_rate'].fillna(0)

In [95]:
batting.dtypes

match_no          int64
match            object
innings           int64
batsman          object
runs              int64
balls             int64
4s                int64
6s                int64
strike_rate     float64
out/ not_out     object
dtype: object

In [96]:
batting.isnull().sum()

match_no        0
match           0
innings         0
batsman         0
runs            0
balls           0
4s              0
6s              0
strike_rate     0
out/ not_out    0
dtype: int64

In [109]:
batting.to_csv('batting_.csv', index=False)

In [110]:
batting = pd.read_csv('batting_.csv')

In [112]:
batting.sample(2)

,match_no,match,innings,batsman,runs,balls,4s,6s,strike_rate,out/ not_out
205,12,Biratnagar Kings vs Chitwan Rhinos,2,Narayan Joshi,4,14,0,0,28.57,out
86,6,Pokhara Avengers vs Sudur Paschim Royals,1,Harmeet Singh,4,6,1,0,66.66,out

In [ ]:
# For match no 21 to 30

In [3]:
# Batting Stats
batting_2 = pd.read_csv("batting_stats_2.csv")
batting_2.head()

,match_no,match,innings,batsman,dismissal,runs,balls,minutes,4s,6s,strike_rate
0,21,Karnali Yaks vs Pokhara Avengers,1,Kushal Bhurtel (c),c Yadav b Watt,18,17,-,3,1,105.88
1,21,Karnali Yaks vs Pokhara Avengers,1,Adam Rossington †,not out,108,58,-,11,7,186.20
2,21,Karnali Yaks vs Pokhara Avengers,1,Jason Roy,c Panchal b Yadav,46,34,-,2,3,135.29
3,21,Karnali Yaks vs Pokhara Avengers,1,Dhananjaya Lakshan,not out,23,11,-,3,1,209.09
4,21,Karnali Yaks vs Pokhara Avengers,2,Mark Watt,c Das b Thagunna,59,34,-,4,5,173.52

In [5]:
batting_2['out/ not_out'] = batting_2['dismissal'].apply(lambda x: "not out" if x == 'not out' else "out")

In [7]:
batting_2.drop('dismissal',axis=1, inplace=True)
batting_2.drop('minutes',axis=1, inplace=True)

In [8]:
batting_2.columns

Index(['match_no', 'match', 'innings', 'batsman', 'runs', 'balls', '4s', '6s',
       'strike_rate', 'out/ not_out'],
      dtype='object')

In [10]:
batting_2['batsman'] = batting_2['batsman'].str.replace(r'†', '', regex=True)

In [12]:
print(f"Shape: {batting_2.shape}")
print("===========================")
print(f"Checking datatypes: \n\n {batting_2.dtypes}")

Shape: (206, 10)
===========================
Checking datatypes:

 match_no          int64
match            object
innings           int64
batsman          object
runs              int64
balls             int64
4s                int64
6s                int64
strike_rate     float64
out/ not_out     object
dtype: object

In [14]:
batting_2.isnull().sum()

match_no        0
match           0
innings         0
batsman         0
runs            0
balls           0
4s              0
6s              0
strike_rate     0
out/ not_out    0
dtype: int64

In [16]:
batting_2.to_csv('batting_2.csv', index=False)

In [17]:
batting1 = pd.read_csv("batting_.csv")
batting2 = pd.read_csv("batting_2.csv")

# Combining vertically 
batting_combined = pd.concat([batting1, batting2], ignore_index=True)
batting_combined.to_csv("batting_combined.csv", index=False)

In [19]:
batting_combined.shape

(546, 10)

In [38]:
batting_combined[batting_combined['batsman'] == 'Rishi Dhawan']

,match_no,match,innings,batsman,runs,balls,4s,6s,strike_rate,out/ not_out
386,23,Kathmandu Gorkhas vs Pokhara Avengers,2,Rishi Dhawan,54,31,3,2,174.19,out

##### **Bowling**

In [105]:
bowling = pd.read_csv("bowling_stats.csv")
bowling.head()

,match_no,match,innings,bowler,overs,maidens,runs,wickets,economy,wides,noballs
0,1,Janakpur Bolts vs Kathmandu Gorkhas,1,Karan KC,4.0,0,30,1,7.50,0,0
1,1,Janakpur Bolts vs Kathmandu Gorkhas,1,Rashid Khan,2.0,0,20,0,10.00,0,0
2,1,Janakpur Bolts vs Kathmandu Gorkhas,1,Milind Kumar,4.0,0,15,3,3.75,0,0
3,1,Janakpur Bolts vs Kathmandu Gorkhas,1,Gerhard Erasmus,3.0,0,23,0,7.66,0,0
4,1,Janakpur Bolts vs Kathmandu Gorkhas,1,Shahab Alam,4.0,0,20,1,5.00,0,0

In [106]:
bowling.drop('wides', axis=1, inplace=True)
bowling.drop('noballs', axis=1, inplace=True)

In [107]:
bowling.groupby('bowler')['innings'].sum().sort_values(ascending=False)

bowler
Santosh Yadav      9
Shahab Alam        9
Karan KC           9
Rashid Khan        9
Harmeet Singh      8
                  ..
Sachin Bhatt       1
Sangeeth Cooray    1
Sam Heazlett       1
Sunny Patel        1
Wayne Parnell      1
Name: innings, Length: 75, dtype: int64

In [115]:
print(f"Shape: {bowling.shape}")
print("===========================")
print(f"Checking datatypes: \n\n {bowling.dtypes}")

Shape: (261, 9)
===========================
Checking datatypes:

 match_no      int64
match        object
innings       int64
bowler       object
overs       float64
maidens       int64
runs          int64
wickets       int64
economy     float64
dtype: object

In [114]:
bowling.isnull().sum()

match_no    0
match       0
innings     0
bowler      0
overs       0
maidens     0
runs        0
wickets     0
economy     0
dtype: int64

In [116]:
bowling.to_csv('bowling_.csv', index=False)

In [118]:
bowling = pd.read_csv("bowling_.csv")
bowling.sample(2)

,match_no,match,innings,bowler,overs,maidens,runs,wickets,economy
12,1,Janakpur Bolts vs Kathmandu Gorkhas,2,Lahiru Samarakoon,1.0,0,6,0,6.0
60,5,Chitwan Rhinos vs Lumbini Lions,2,Kushal Malla,4.0,0,16,0,4.0

In [21]:
bowling_2 = pd.read_csv("bowling_stats_2.csv")
bowling_2.head()

,match_no,match,innings,bowler,overs,maidens,runs,wickets,economy,wides,noballs
0,21,Karnali Yaks vs Pokhara Avengers,1,Bipin Sharma,3.0,0,27,0,9.0,0,0
1,21,Karnali Yaks vs Pokhara Avengers,1,Nandan Yadav,4.0,0,34,1,8.5,3,0
2,21,Karnali Yaks vs Pokhara Avengers,1,Sompal Kami,4.0,0,50,0,12.5,0,0
3,21,Karnali Yaks vs Pokhara Avengers,1,Mark Watt,3.0,0,24,1,8.0,0,0
4,21,Karnali Yaks vs Pokhara Avengers,1,Dipendra Rawat,2.0,0,15,0,7.5,0,0

In [23]:
bowling_2.drop('wides', axis=1, inplace=True)
bowling_2.drop('noballs', axis=1, inplace=True)

In [24]:
print(f"Shape: {bowling_2.shape}")
print("===========================")
print(f"Checking datatypes: \n\n {bowling_2.dtypes}")

Shape: (155, 9)
===========================
Checking datatypes:

 match_no      int64
match        object
innings       int64
bowler       object
overs       float64
maidens       int64
runs          int64
wickets       int64
economy     float64
dtype: object

In [25]:
bowling_2.isnull().sum()

match_no    0
match       0
innings     0
bowler      0
overs       0
maidens     0
runs        0
wickets     0
economy     0
dtype: int64

In [26]:
bowling_2.to_csv('bowling_2.csv', index=False)

In [28]:
bowling1 = pd.read_csv("bowling_.csv")
bowling2 = pd.read_csv("bowling_2.csv")
bowling_combined = pd.concat([bowling1, bowling2], ignore_index=True)
bowling_combined.to_csv('bowling_combined.csv', index=False)

In [33]:
bowling_combined[bowling_combined['bowler'] == 'Ranjit Kumar']

,match_no,match,innings,bowler,overs,maidens,runs,wickets,economy
152,12,Biratnagar Kings vs Chitwan Rhinos,2,Ranjit Kumar,4.0,0,21,5,5.25
184,15,Chitwan Rhinos vs Kathmandu Gorkhas,1,Ranjit Kumar,4.0,0,28,2,7.00
256,20,Chitwan Rhinos vs Janakpur Bolts,2,Ranjit Kumar,4.0,0,35,0,8.75
304,24,Chitwan Rhinos vs Sudur Paschim Royals,1,Ranjit Kumar,4.0,0,16,1,4.00
350,27,Chitwan Rhinos vs Pokhara Avengers,2,Ranjit Kumar,4.0,0,16,0,4.00

In [35]:
bowling_combined[bowling_combined['bowler'] == 'Kushal Malla']

,match_no,match,innings,bowler,overs,maidens,runs,wickets,economy
17,2,Chitwan Rhinos vs Karnali Yaks,1,Kushal Malla,3.0,0,29,0,9.66
60,5,Chitwan Rhinos vs Lumbini Lions,2,Kushal Malla,4.0,0,16,0,4.00
154,12,Biratnagar Kings vs Chitwan Rhinos,2,Kushal Malla,3.5,0,46,1,12.00
255,20,Chitwan Rhinos vs Janakpur Bolts,2,Kushal Malla,1.0,0,9,0,9.00
302,24,Chitwan Rhinos vs Sudur Paschim Royals,1,Kushal Malla,4.0,0,36,0,9.00

##### **Match Results**

In [23]:

# # Match Results
# match_results = pd.read_csv("match_results.csv")
# match_results.head()

In [124]:
# Players 
players_info = pd.read_csv("players_full_info.csv")
players_info.head(5)

,player,batting_style,bowling_style,playing_role,team,country,image_url
0,Aaditya Mahata,NaN,NaN,NaN,NaN,NaN,NaN
1,Aakash Chand,Right-handed,Right-arm medium,Bowler,Nepal,NaN,NaN
2,Aakash Tripathi,NaN,NaN,NaN,NaN,NaN,NaN
3,Aarif Sheikh,Right-handed,Right-arm medium,Batsman,Nepal (2015–present),NaN,https://upload.wikimedia.org/wikipedia/commons...
4,Aasif Sheikh,NaN,NaN,NaN,NaN,NaN,https://upload.wikimedia.org/wikipedia/commons...

In [125]:
players_info[players_info['player'] == 'Faf du Plessis']

,player,batting_style,bowling_style,playing_role,team,country,image_url
117,Faf du Plessis,Right-handed,Right-arm leg-break,Top-order batter,South Africa (2011–2021),NaN,https://upload.wikimedia.org/wikipedia/commons...

In [128]:
players_info['team'] = players_info['team'].str.split('(').str[0].str.strip()
players_info.sample(2)

,player,batting_style,bowling_style,playing_role,team,country,image_url
113,Dhruv Parashar,Right-handed,Right-arm off spin,All-rounder,United Arab Emirates,NaN,NaN
6,Abhishesh Gautam,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
players_info.drop('country', axis=1, inplace=True)

In [130]:
players_info.columns

Index(['player', 'batting_style', 'bowling_style', 'playing_role', 'team',
       'image_url'],
      dtype='object')

In [131]:
players_info['team'].value_counts()

team
Nepal                   32
Namibia                  4
England                  3
Australia                3
New Zealand              3
Afghanistan              3
Sri Lanka                3
South Africa             3
United States            3
Scotland                 2
Pakistan                 2
Uganda                   2
Netherlands              1
Italy                    1
United Arab Emirates     1
India                    1
Name: count, dtype: int64

In [132]:
print(f"Shape: {players_info.shape}")
print("===========================")
print(f"Checking datatypes: \n\n {players_info.dtypes}")

Shape: (135, 6)
===========================
Checking datatypes:

 player           object
batting_style    object
bowling_style    object
playing_role     object
team             object
image_url        object
dtype: object

In [133]:
players_info.isnull().sum()

player            0
batting_style    58
bowling_style    70
playing_role     63
team             68
image_url        91
dtype: int64

In [134]:
players_info.to_csv('players_info_.csv')